CREATE TABLE short_url
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    short_code      VARCHAR(255),
    original_url    TEXT                                    NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expiration_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_short_url PRIMARY KEY (id)
);